name: userapp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-5.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.4
  google_fonts: ^2.3.2


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


